package com.aut.pdc.mike.gui;

import javax.swing.JOptionPane;
import com.aut.pdc.mike.gamemodel.Player;

/**
 * Register Frame
 * @author Minghao Yang
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register(Player player) {
        this.player = player;
        initComponents();
        this.registerMess.setVisible(false);
    }

    private Register() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        registerMess = new javax.swing.JOptionPane();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        returnBtn.setBackground(new java.awt.Color(177, 222, 121));
        returnBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnBtn.setText("RETURN");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn);
        returnBtn.setBounds(250, 410, 119, 40);

        submitBtn.setBackground(new java.awt.Color(177, 222, 121));
        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn);
        submitBtn.setBounds(250, 360, 116, 40);

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTxt);
        passwordTxt.setBounds(240, 300, 170, 30);

        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTxt);
        usernameTxt.setBounds(240, 230, 170, 30);

        jLabel2.setBackground(new java.awt.Color(172, 222, 121));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aut/pdc/mike/gui/img/register.jpg"))); // NOI18N
        jLabel2.setSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 600);

        registerMess.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        getContentPane().add(registerMess);
        registerMess.setBounds(140, 250, 350, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed
    /**
     * Return button action performed
     * @param evt 
     */
    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainMenu mm = new MainMenu(player);
        mm.setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed
    /**
     * Submit button action performed
     * @param evt 
     */
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String userName = usernameTxt.getText();
        String password = passwordTxt.getText();
        if(!"".equals(userName.trim()) && !"".equals(password.trim())){
        //Create a new game account
        this.messageTxt = player.createAccount(userName, password);
        //Show the register result to the player
        registerMess.showMessageDialog(null, messageTxt, "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }else{
        registerMess.showMessageDialog(null, "The username and password could not be empty!", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
        usernameTxt.setText("");
        passwordTxt.setText("");
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JOptionPane registerMess;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
    public Player player;
    private String messageTxt;
}
